#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 17:38:18 2017

@author: Muriel
"""
target=0
comput=0
small=6
medium=9
large=20

def nuggetnumber(target):
    for x in range(0,target):
        for y in range(0,target):
            for z in range(0,target):
                if target==(small* x+ medium * y+ large * z):
                    return True
    return False


    
while comput<7:
        if nuggetnumber(target)==True:
            comput+=1
        if nuggetnumber(target)==False:
            largest=target
            comput=0
        target+=1
print("the highest number of Chicken nugget you can not purchase is",largest)

    
