#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 13:33:57 2017

@author: Muriel
"""

import random

def print_header():
    print("\tWelcome to 'Guess My Number'!")
    print("\tI'm going to guess your number between 1 and 100.")
    print("\tI will try to guess it in as few attempts as possible.\n")


def print_footer(guess, tries):
    print("I guessed it! The number was",guess_number)
    print("And it only took me", tries, "tries!\n")
    print("\n\nPress the enter key to exit.")    
    
def main():
    # print the greeting banner
    print_header()
    
    # set the initial values
    
    guess_number=random.randint(1,100)
    guess_number=int(input("take a guess"))
    guess=random.randint(1,100)
    Lowest = 1
    Highest = 100
    tries = 1
    
    while  guess!=guess_number:
        if guess>guess_number:
            print("lower")
            Lowest=Lowest
            Highest=guess
            guess=(Lowest+guess)//2
            
        else:
            print("higher")
            Lowest=guess
            Highest=Highest
            guess=(Highest+guess)//2
        tries+1
        guess= int(input ("take a guess  "))
    print_footer(guess, tries)

main()